// Copyright (C) 2025 TKSoft, Konstantin Terskikh, kostus.online.1974@yandex.ru, kostus.online@gmail.com
// Permission is hereby granted,free of charge,
// to any person obtaining a copy of this software and associated documentation files(the"Software"),
// to deal in the Software without restriction,including without limitation the rights to use,copy,modify,merge,
// publish,distribute,sublicense,and/or sell copies of the Software,
// and to permit persons to whom the Software is furnished to do so,subject to the following conditions:
// The above copyright notice and this permission notice shall be included in all copies or substantial
// portions of the Software.
// THE SOFTWARE IS PROVIDED"AS IS",WITHOUT WARRANTY OF ANY KIND,EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
// LIABLE FOR ANY CLAIM,DAMAGES OR OTHER LIABILITY,WHETHER IN AN ACTION OF CONTRACT,TORT OR OTHERWISE,ARISING
// FROM,OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

= Анализ технического собеседования.

== Условия.

По каким критериям необходимо оценивать видео:

- Какую информацию дал о себе разработчик? Достаточно ли ее для того, чтобы сформировать целостный образ?
- Выделите и запишите, было ли что-то лишнее в рассказе и чего могло не хватать.
- Как кандидат отвечает на вопросы? Достаточно полно?
Выделите, на какие вопросы кандидат ответил развернуто, а какие ответы требовали дополнения.
Подумайте и запишите.
- Как ведет себя разработчик?
Обратите внимание на моторику рук и тела, интонации голоса, насколько развернутыми были ответы на вопросы.
- Опишите, какое впечатление складывается на протяжении всего интервью и что остается после.
 Что стоило и что не стоило упоминать соискателю?

== Общие соображения.

=== Хорошо
- Общая грамотность, хотя и не оратор;
- Институт, C#/ MathLab etc. - уже хорошо;

=== Стоит обратить внимание:
- Стоит ли вспоминать про школу и про свои увлечения? Многословность про начала своего увлечения.

 Может стоит начинать рассказ о себе, как о разработчике, с задачи, которую удалось решить именно с помощью программирования?

 Достаточно: "Учусь в вузе, изучаю C# и Java. Есть три проекта% ...".

- Вопрос от интервьюера: Почему Java?

 Ответ: про востребованность, про ЗП и т.п.

 Кажется, что надо про стройность языка и платформы, про открытость, про сообщество.

- Вопрос: Что такое Object?

 Ответ в основном про полиморфизм.

 Кроме этого надо про "базовость" этого класса, про базовые методы: equals, hashCode etc.

- Признание в том, что слишком часто пользовался автогенерацией кода при ответе на вопрос про equals.

- Интервьюер начал слишком много говорить сам, навязывая уже "детские" наводящие вопросы.

 Обучение по ходу интервью. По сути это уже провал.

 Интервьюер говорит гораздо больше, чем интервьюируемый.

 Сразу, по своей вине, занял ведомую позицию.

 Наводящие вопросы про правильность своих ответов задаёт уже интервьюируемый.

- Много "ну", "не знаю", "и так далее", "ну да, но...".
- "Торможение" нарастает лавинообразно.
- Лицо слишком близко к экрану.
- Голос недостаточно низкий.

=== Уроки из интервью

Первый провал: нет чёткого ответа про Object, про equals/hashCode.
Интервьюер стал задавать "детские" вопросы с некоторым уже раздражением.

Полный провал в equals по использованию в сравнениях обращений к private полям - к private полям можно обращаться
из методов того же класса. Вообще полный провал на equals при демонстрации базовых конструкций языка.

_(Конкретика для себя: допустимо ли внутри equals использовать сравнение не по геттерам, а по полям непосредственно?
Кажется, что надо по геттерам.)_

Усиление первого провала: интервью превратилось в занятие по Java.

Надо:

- уметь коротко рассказать о себе и о своём программировании;
- чётко отвечать на "базу": Object, equals/hashCode (правила equals);
- зачем сеттеры и геттеры? почему это лучше, чем просто открытые поля?
- массивы и классы-коллекции - чем выгодны, сравнения, выбор того или другого
("generic-параметры не могут быть примитивами" - коротко и ясно);
